### ISSUE TITLE
34 bash blocks use $CLI_PATH in a block that never defines it, so the resolver runs `node ""`

### ISSUE THREAD

**Issue by MrityunjayBhardwaj** [MrityunjayBhardwaj/anvi#344]
## Problem

Each fenced `bash` block in a workflow runs as its own shell. Shell state — variables
included — does not survive from one block to the next. So a workflow that sets
`CLI_PATH` in one step and uses `$CLI_PATH` in another is running `node ""` in the
second.

This is not a new theory. It was found and fixed for one file while closing #338, and
`test/orient-live-state.test.js` pins it there: *"the block that runs `planning-root`
also defines CLI_PATH"*. Nothing generalised the check, so the rest of the directory
still has it.

## Measured at `294ebfe`

**34 blocks across 16 files** use `$CLI_PATH` without defining it in the same block.

`add-phase.md` is the shortest illustration — the variable is set in `<step name="add">`
and used in `<step name="commit">`:

```
<step name="add">
CLI_PATH="$HOME/.claude/anvi/bin/anvi-tools.cjs"
node "$CLI_PATH" phase add "${DESCRIPTION}"
</step>
<step name="commit">
node "$CLI_PATH" commit "docs: add phase — ${DESCRIPTION}" --files ".../ROADMAP.md"
</step>
```

The 16: `add-phase`, `complete-milestone`, `discuss-phase`, `do`, `execute-phase`,
`insert-phase`, `new-milestone`, `new-project`, `pause-work`, `plan-phase`, `progress`,
`quick`, `remove-phase`, `research-phase`, `resume-project`, `stats`.

Several files carry a `<cli_resolution>` block at the top that defines `CLI_PATH` once.
That convention is the bug: it is correct only if every later block shares that shell,
and none of them do.

## How this fails, and why it is a different severity from #340

Loudly, which is the one piece of good news. `node ""` exits with *Cannot find module*,
so the step visibly fails rather than silently reading nothing. That is why this is
filed apart from #340 rather than folded into it — #340 is a **silent** failure class
and this is a noisy one, and mixing them in one sweep would put two different arguments
in one diff.

But one interaction is worth stating, because it is the reason this was found while
working #340. `do.md:95` already does the right thing —
`ls "$(node "$CLI_PATH" planning-root --raw)"/` — in a block that never defines
`CLI_PATH`. The resolver call itself is what fails. **A workflow can satisfy "resolve,
never spell" and still resolve nothing**, so closing #340 does not imply this is closed.

## Proposed shape

1. A guard asserting every bash block that uses `$CLI_PATH` also defines it. Derived
   from the directory, not a list, so the 17th file fails rather than passes.
2. Define `CLI_PATH` in each block that uses it, and retire the top-of-file
   `<cli_resolution>` convention wherever it is doing nothing — a block that appears to
   set up state for later blocks teaches the wrong model to the next author.
3. Falsified both ways: the guard must go red on a block that uses the variable without
   defining it, and must not go red on a block that defines it.

## Success criteria

- [ ] A guard reddens on a bash block using `$CLI_PATH` without defining it
- [ ] All 34 blocks define it, or are shown not to need it
- [ ] The dead `<cli_resolution>` convention is removed or made honest
- [ ] Falsified: the guard is shown to go red by name for each class it claims to catch

**Comment by MrityunjayBhardwaj** [comment]
## Re-measured before starting — the count is right, the scope is not

Re-running the measurement at `294ebfe` before touching anything, because the last two
sweeps started from a filed classification that turned out to be wrong.

**The headline number is exact.** 34 blocks across 16 files, and the sixteen names in the
issue match the sixteen the measurement produces, one for one. No correction there.

**But the corpus was `workflows/` only, and the defect is not confined to it.** Scanning
the rest of the shipped tree the same way finds two more:

| site | fence | kind |
|---|---|---|
| `agents/anvi-executor.md:235` | ` ```bash ` | **the same defect exactly** — three `node "$CLI_PATH" state …` calls in a block that never assigns it |
| `agents/anvi-debugger.md:278` | untagged fence | documentation snippet (`## File Location`) that builds `DEBUG_DIR` from `$CLI_PATH` |

So the worklist is **36 blocks across 18 files** — 35 executable, plus one documentation
fence that would break the same way if anyone ran it. The executor one matters more than
its count suggests: an agent's blocks run in exactly the same one-shell-per-block way a
workflow's do, so it fails identically, and `agents/` was simply never looked at.

Worth noting *why* it was missed, since it is a repeatable trap rather than an oversight:
the untagged fence is invisible to any check written as "scan bash blocks". A guard
selecting on the language tag would pass that file forever. The guard should select on
**content** — a fence that uses the variable — and let the tag be evidence, not the filter.

## Not the same class, and deliberately out of scope

The same scan asks a broader question: which shell variables are used in a fenced block
that never assigns them? Twelve names come back. Eleven of them — `${PHASE}`,
`${DESCRIPTION}`, `${VERSION}`, `${KEY}`, `${VALUE}` and so on — are **placeholders the
model substitutes before running**, not shell state, and they are working as intended.

The discriminator is worth writing down because it is also the reason this bug is
invisible: a placeholder is *substituted*, a shell variable is *inherited*. `CLI_PATH`
reads as the second — the file assigns it, just in a different block — so it gets passed
through verbatim instead of being filled in. A name that is never assigned anywhere in the
file never creates this confusion. **The assignment somewhere else in the file is what
makes it a bug, not the absence of one.**

That also sharpens success criterion 1. A guard that asserts "every block using
`$CLI_PATH` defines it" is a guard for one name, which is the thing this issue criticises
about the fix that closed the earlier one. The generalisable form is: *a fenced block that
uses a variable the same file assigns elsewhere, but that block does not assign, is a
cross-block state assumption.* That catches the 17th file and the next variable, without
firing on the eleven placeholders.

## Confirmed stable across the open PR this is blocked on

This is deliberately queued behind the workflows-resolve-the-planning-tree PR, since that
one rewrites fifteen of these same files. Measured on that branch: uses of `$CLI_PATH` go
from 50 to 65, and **all fifteen new ones define it in their own block**. The
used-without-defining set is identical — same files, same per-file counts, only line
numbers shift. So the worklist above survives that merge unchanged, and the shape of the
fix does not need to be re-derived afterwards.

**Comment by MrityunjayBhardwaj** [comment]
## The severity in this issue is backwards — measured, not argued

This issue says the good news is that the failure is loud:

> Loudly, which is the one piece of good news. `node ""` exits with *Cannot find module*,
> so the step visibly fails rather than silently reading nothing.

That is the reason it was filed apart from the spelled-path issue rather than folded into
it. It is wrong, and in the direction that matters.

```
$ env -u CLI_PATH bash -c 'node "$CLI_PATH" planning-root --raw'
exit code : 0
stdout+err: []
bytes     : 0
```

**Exit 0, zero bytes.** Not a failure — a silent success.

The mechanism, since knowing *why* makes it predictable rather than a curiosity:
`node ""` treats an empty path as "read the script from **stdin**", and a workflow
block's stdin is empty, so it runs nothing and exits clean.

```
$ echo 'console.log("executed from stdin:", 40+2)' | node ""
executed from stdin: 42
```

The contrast is what makes this easy to get wrong. A *non-empty* missing path is loud,
which is what the filed reasoning was picturing:

```
$ node "/nope/missing.cjs" planning-root
node:internal/modules/cjs/loader:1458
  throw err;          # Cannot find module — non-zero exit
```

An unset variable expands to the empty string, not to a wrong path, so this class never
reaches the loud branch.

### What changes

- **The two issues are the same severity class after all.** Both are silent. This one is
  arguably worse: a spelled path at least fails at a *visible* place, whereas here a step
  reports success having done nothing, and every later step proceeds on that basis.
- **The "different severity" argument for separating them was unsound** — though keeping
  them in separate changes still stands on its own, since one diff should carry one
  argument.
- The success criteria are unaffected; only the risk assessment moves, and it moves up.

Worth noting how it was found, because it is the recurring shape: the claim was inferred
from how a missing module behaves, which is true of the case that was pictured and not of
the case that occurs. Running the one-line control costs seconds and was not run when the
issue was filed — including by me, twice, before I ran it.
